config/routes.rb
Rails.application.routes.draw do
  resources :categories

  devise_for :users

   root 'books#index'

  resources :books do
      member do
        get 'new' 
        get 'show'
        get 'create'
        get 'edit'
        get 'show_book'
        patch 'update'
        delete 'destroy_user'
      end
      collection do
       get 'user_index'
      end
    end

end

app/models/book.rb
class Book < ActiveRecord::Base
	has_attached_file :book_image , :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  	validates_attachment_content_type :book_image, :content_type => /\Aimage\/.*\Z/
end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
	before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception

  def configure_permitted_parameters
  	# Config more field to devise 
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(  :email, :name , :about, :password, :password_confirmation, :remember_me, :role_id ) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(  :email, :name, :about, :password, :password_confirmation, :current_password, :role_id ) }
	end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
before_action :authenticate_user!, :except => 'index'
	
	# Get all books 
	def index
		@books = Book.all.where("title LIKE ?" , "%#{params[:search]}%")
		# Filter by category if need
		@books = Book.all.where("title LIKE ?" , "%#{params[:search]}%").where(:category => params[:category_filter]) if params[:category_filter].present?
	end

	# Get all user list
 	def user_index
 		@users = User.all
 	end

 	# Get new object of book
	def new
		@book = Book.new
	end

	# Save book in database
	def create
		@book = Book.new(book_params)
		@book.save
		redirect_to books_path
	end

	# Get book object by id
	def edit
		@book = Book.find(params[:id])
	end

	# Show a book 
	def show_book
		@book = Book.find(params[:id])
	end

	# Update book database
	def update
		@book = Book.find(params[:id])
		@book.update(book_params)
		redirect_to books_path
	end

	# Delete book 
	def destroy
		@book = Book.find(params[:id])
		@book.destroy
		redirect_to books_path
	end

	# Delete user
	def destroy_user
		@user = User.find(params[:id])
		@user.destroy
		redirect_to :back
	end

	private
    # Never trust parameters from the scary internet, only allow the white list through.
	def book_params
		params.require(:book).permit(:book_image, :title, :description, :category, :author)
	end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/books/edit.html.erb
<div style="margin-left: 400px; margin-top: 15px;">
<h3>Edit  Book</h3>
<%= form_for @book, :url => {:controller => "books", :action => "update"}, :html => { :multipart => true }, method: :patch do |f| %>

  <%= f.label :title %><br />
  <%= f.text_field :title, :style=>"width: 282px;", :required => true %><br />
  
  <%= f.label :author %><br />
  <%= f.text_field :author , :class => "text_field_library", :required => 'true'%><br />

  <%= f.label :description %><br />
  <%= f.text_field :description , :style=>"width: 282px;" , :required => true%><br />
  
  <%= f.label :category %><br />
   <%= f.select :category, options_for_select(Category.all.collect{|ct| [ct.name, ct.name]},@book.category), {:include_blank => false}, :style=>"width: 282px;" %>

  <%#= f.text_field :category %><br />
    <%= f.label :book_image %><br />
  <%= f.file_field :book_image , :style=>"width: 282px;", :required => true%><br />
  
  <%= f.submit :update%>

<% end %>
</div>

app/views/books/index.html.erb
<h3 style=" text-align: center;">Book List</h3>
<div id="sidebar" class="sidebar-offcanvas col-md-3">
      <div class="col-md-12">
        <ul class="nav nav-pills nav-stacked">
           <div class="checkbox">
							<%= form_tag books_path ,:method => "get" ,:class=>"navbar-form navbar-left" do %>
								<div class="form-group">
								<%= hidden_field_tag :search, params[:search], :id => 'search_field'  ,:class=>"form-control" %> 
									<% Category.all.each do |category| %>
										<% condi = false
										condi = params[:category_filter].include? category.name if params[:category_filter].present?%>
										<li><%=check_box_tag 'category_filter[]', category.name, condi %><%= category.name %></li>
									<%end%>
								</div>
							<li class="active">
								<%= submit_tag "Filter", :name => nil ,:class=>"btn btn-default"%>  
							</li>
							<%end%>
	        </div>
        </ul>
      </div>
  </div>
<div class="row col-md-9">	
	<% @books.each do |book| %>
  <div class="col-sm-4">
  	<div  style="border: 1px solid rgb(221, 72, 20); margin: 1px;text-align: center;">
  	<%=  link_to image_tag(book.book_image.url, :class => 'index_book_image') , show_book_book_path(book)%>
  	<h3 style="word-wrap: break-word;">Title -<%= link_to book.title[0..15], show_book_book_path(book)  %></h3>
  	<h5>Author -<%= book.author[0..25] %></h5>
  	
  	<h5>Description -<%= book.description[0..25] %></h5>
  	<h5>Category -<%= book.category[0..25] %></h5>
  	<h4 style="margin-top: 40px;">
  	<% if current_user.present? %>
  	<% if current_user.id == 1 %>
	  	<%= link_to '', show_book_book_path(book), :class => "show_book", :title => 'show book detail' %>
	    <%= link_to '', edit_book_path(:id => book.id), :class => "edit_book_link" , :title => 'update book'%> 
	    <%= link_to '', { action: :destroy, id: book.id }, method: :delete, data: { confirm: 'Are you sure?' } , :class => "delete_book" , :title => 'delete book'%>
    <% end %>
    <% end %>
    </h4>
    </div>
  </div>  
  <% end %>
</div>

app/views/books/new.html.erb
<div style="margin-left: 400px; margin-top: 15px;">
<h3>Add Books</h3>

<%= form_for :book, :url => books_path, :html => { :multipart => true } do |f| %>
  
  <%= f.label :title %><br />
  <%= f.text_field :title , :class => "text_field_library", :required => 'true'%><br />

  <%= f.label :author %><br />
  <%= f.text_field :author , :class => "text_field_library", :required => 'true'%><br />

  <%= f.label :description %><br />
  <%= f.text_field :description, :class => "text_field_library", :required => 'true' %><br />
  
  <%= f.label :category %><br />
  <%#= f.text_field :category , :class => "text_field_library"%>
  <%= f.select :category, options_for_select(Category.all.collect{|ct| [ct.name, ct.name]}), {:include_blank => false} %><br />

  <%= f.label :book_image %><br />
  <%= f.file_field :book_image, :class => "text_field_library", :required => 'true' %><br />
  
  <%= f.submit :save%>

<% end %>
</div>

app/views/books/show_book.html.erb
<div class="col-xs-6">
  	<h2><%= image_tag @book.book_image.url ,:style => "margin-top: 40px; height: 400px; width: 300px; margin-left: 260px;" %></h2>
</div>
<div class="col-xs-6" style="margin-top: 130px;">
	<h3>Title -<%= @book.title %></h3>
  	<h5>Author -<%= @book.author %></h5>
  	<h5>Description -<%= @book.description %></h5>
  	<h5>Category -<%= @book.category %></h5>
</div>

app/views/books/user_index.html.erb
<div style="width: 600px; margin-top: 15px; margin-left: 400px;">
<h3>User List</h3>
<table class="table table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |u| %>
    <% if u.email != current_user.email %>
      <tr>
        <td><%= u.name %></td>
        <td><%= u.email %></td>
        <td><%= link_to '', { action: :destroy_user, id: u.id }, method: :delete, data: { confirm: 'Are you sure?' } , :class => "delete_user", :title => 'delete user'%></td>
      </tr>
     <% end %> 
    <% end %>
  </tbody>
</table>
</div>

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, :style => 'width: 230px;', :required => true%>
  </div>
  <div class="actions">
    <%= f.submit 'save category' %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<div style="margin-left: 40%;">
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>
</div>

app/views/categories/index.html.erb
<div style="width: 400px; margin-left: 400px;">
<h3>Book Categories</h3>
<table class="table table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= link_to '', category, :class => "show_category"  , :title => 'show category'%></td>
        <td><%= link_to '', edit_category_path(category), :class => "edit_category_link"  , :title => 'update category'%></td>
        <td><%= link_to '', category, method: :delete, data: { confirm: 'Are you sure?' }, :class => "delete_category"  , :title => 'delete category'%></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'New Category', new_category_path %>
</div>

app/views/categories/new.html.erb
<div style="margin-left: 400px;">

<h3>New Category</h3>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>
</div>

app/views/categories/show.html.erb
<div style="margin-left: 40%;">

<p id="notice"><%= notice %></p>

<h3>
  <strong>Name:</strong>
  <%= @category.name %>
</h3>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>
</div>

app/views/layouts/[LAYOUT_NAME].html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Library" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Library</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Link1", "/path1"  %></li>
            <li><%= link_to "Link2", "/path2"  %></li>
            <li><%= link_to "Link3", "/path3"  %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2015</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Library</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<ul class="nav nav-tabs" style="background-color: rgb(221, 72, 20);">
		<li role="presentation"><%= link_to 'Home', books_path , :class => 'navbar-link'%></li>
 		<% if user_signed_in? %>	
			<% if current_user.id == 1 %>
			  <li role="presentation">  <%= link_to "Add Book", new_book_path , :class => 'navbar-link'%></li>
			  <li role="presentation"><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link'  %></li>
			  <li role="presentation">  <%= link_to "Categories", categories_path , :class => 'navbar-link'%></li>
			  <li role="presentation">  <%= link_to "Users", user_index_books_path, :class => 'navbar-link' %></li>
		  	<% end %>
<<<<<<< HEAD
		  	<%= form_tag books_path ,:method => "get" ,:class=>"navbar-form navbar-left" do %>
        <div class="form-group">
           <%= text_field_tag :search, params[:search], :id => 'search_field'  ,:class=>"form-control" %>     
       
        </div>
       <%= submit_tag "Search", :name => nil ,:class=>"btn btn-default"%>  
       	<%end%>
=======
			<%= form_tag books_path ,:method => "get" ,:class=>"navbar-form navbar-left" do %>
				<div class="form-group">
					<%= text_field_tag :search, params[:search], :id => 'search_field'  ,:class=>"form-control" %> 
				</div>
				<%= submit_tag "Search", :name => nil ,:class=>"btn btn-default"%>  
			<%end%>
>>>>>>> 81e81b17861dfe97be6b6091ae1782bdef410761
		  	<li role="presentation" style=" float: right;"><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
		  	<li role="presentation" class="active" style="margin-top: 11px; float: right;"><strong class = 'navbar-link' ><%= current_user.email %></strong></li>
		  	
	  	<% else %>
	  <li role="presentation" style=" float: right;"><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'%> </li>
	  <li role="presentation" style=" float: right;"><%= link_to "Login", new_user_session_path, :class => 'navbar-link' %></li>
<% end %>  
</ul>

<%= yield %>

</body>
</html>